# Nearest-Neighbor Classification

In [1]:
import pandas as pd
df = pd.DataFrame([
    [  1 ,   7 ,  1 ,   1 ,  "spo" ],
    [  2 ,  13 ,  0 ,   1 ,  "spo" ],
    [  3 ,   8 ,  2 ,   1 ,  "spo" ],
    [  4 ,   7 ,  2 ,   3 ,  "spo" ],
    [  5 ,   2 ,  1 ,   0 ,  "sci" ],
    [  6 ,   1 ,  0 ,   1 ,  "sci" ],
    [  7 ,   2 ,  2 ,   1 ,  "sci" ],
    [  8 ,  12 ,  8 ,  11 ,  "his" ],
    [  9 ,   7 ,  3 ,   5 ,  "his" ],
    [ 10 ,   6 ,  5 ,   8 ,  "his" ]],
    columns=[  "DocId" ,  "$X_p$" ,  "$X_l$" ,  "$X_d$" ,  "$Y$" ])

You are given a collection of text documents that each have been classified according to their content into the three classes
*sports*, *scientific*, and *historical*.

Furthermore, three integer features $(X_p, X_l, X_d)$ have been obtained for each document,
by detecting named entities and tagging each entity as *person*, *location*, or *date*,
and counting the number of times each kind of entity occurs.

For each training document, you know $X_p, X_l, X_d$ and the class label $Y = \{\text{spo}, \text{sci}, \text{his}\}$:

In [2]:
df

DocId  $X_p$  $X_l$  $X_d$  $Y$
0      1      7      1      1  spo
1      2     13      0      1  spo
2      3      8      2      1  spo
3      4      7      2      3  spo
4      5      2      1      0  sci
5      6      1      0      1  sci
6      7      2      2      1  sci
7      8     12      8     11  his
8      9      7      3      5  his
9     10      6      5      8  his

a) Compute the most likely class for $x=(5,4,3)$ using the $k$-nearest neighbor classifier with $k=3$ and show how you arrived at your solution.
Use the Euclidean distance function and majority voting.

In [3]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

X = df.iloc[:,1:4].values
y = df.iloc[:,4].values

print(X)
print(y)

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y) 

print("prediction:", neigh.predict([[5,4,3]]))

[[ 7  1  1]
 [13  0  1]
 [ 8  2  1]
 [ 7  2  3]
 [ 2  1  0]
 [ 1  0  1]
 [ 2  2  1]
 [12  8 11]
 [ 7  3  5]
 [ 6  5  8]]
['spo' 'spo' 'spo' 'spo' 'sci' 'sci' 'sci' 'his' 'his' 'his']
prediction: ['spo']


b) Reduce the data set to the mean vectors of each class only.
Compute the most likely class for $x$ using the nearest-neighbor classifier on this reduced data set
and show how you arrived at your solution. Use the Euclidean distance function.

In [6]:
#print(X[0:3])
#print(np.mean(X[0:3], axis=0))
newX = np.array([np.mean(X[0:3], axis=0), np.mean(X[4:6], axis=0), np.mean(X[7:9], axis=0)])
newy = np.array(["spo", "sci", "his"])

#print(newX)

neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(newX, newy) 

print("prediction:", neigh.predict([[5,4,3]]))

prediction: ['sci']


Briefly discuss why the results of the $k$-nearest neighbor classifier could be different from
the results obtained by using the nearest-mean classifier from the previous part.

Beim k-nearest neighbor ist der Testpunkt am nächsten zu zwei Punkten der Klasse "spo". Bei nearest-mean am nächsten zum Mittelwert von "sci".

# Probabilistic Tic-Tac-Toe

In this exercise we will train a probabilistic model to play Tic-Tac-Toe with us. To do so, download the UCI Tic-Tac-Toe dataset (https://archive.ics.uci.edu/ml/datasets/Tic-Tac-Toe+Endgame).

a) Load the data and make yourself familiar with the data representation. Write code to display a field in your shell using ASCII characters. Write a function `chose_cell` that given the data and using Bayes' Theorem, returns the best cell (as number from 0 to 8) for the first turn of player $X$?

In [5]:
import pandas as pd
df = pd.read_csv('tic-tac-toe.data')

def display_field(field):
    # TODO

def chose_cell(df):
    # TODO

print(chose_cell(df))
test_field = ['b' for i in range(9)]
test_field[chose_cell(df)] = 'x'
display_field(test_field)

IndentationError: expected an indented block (<ipython-input-5-b27da7eb59ac>, line 7)

b) Adapt your function `chose_cell` to also take the current board situation into consideration and returns the best *blank* cell (as number from 0 to 8) for any turn of player $X$. Use the interactive shell to play against it.

In [ ]:
def chose_cell(field,df):
    # TODO

# Game functions
game_field = []
def init_game_field():
    global game_field # Uses global variables instead of local
    game_field = ['b' for i in range(9)]
    make_ai_turn()

def make_ai_turn():
    global df, game_field
    # TODO
    display_field(game_field)

def make_human_turn(position):
    global game_field
    # TODO
    display_field(game_field)

In [ ]:
# Play here!

c) Create a function `chose_cell_lookahead` that returns the best *blank* cell, for which winning probabilities of player $X$ are best after the player $O$'s turn using Bayes' Theorem. Do you expect to obtain different results? Test your theories by playing against both functions.

In [ ]:
def chose_cell_lookahead(field,df):
    # TODO

In [ ]:
# Play here!

# Traffic Count imputation

In this exercise we want to use the K Nearest-Neighbor algorithm for traffic prediction. In moodle you can find the file `luxembourg_counts.csv` which contains simulated data from the city of Luxembourg. Our task is to predict the average number of vehicles (counts) in a given region from the morning hours 7:00 to 11:00. To tackle this problem, Luxembourg has been split into multiple grid cells. Each row in `luxembourg_counts.csv` represents one grid cell (identified by its latitude and logitude coordinates) followed by its average vehicle count in the given time slice.

a) Load the data and plot a histogram of traffic counts. Compute a $20\%$ test split, which will be used to judge the algorithms afterwards.

In [8]:
import pandas as pd
df = pd.read_csv('luxembourg_counts.csv')

# TODO
df

Unnamed: 0   latitude  longitude      price
0              0  49.599549   6.149829   1.340000
1              1  49.596630   6.152234  17.386935
2              2  49.601240   6.142613  30.052432
3              3  49.584429   6.166410   0.724412
4              4  49.610775   6.106364  36.644286
5              5  49.609812   6.101694   2.908788
6              6  49.596276   6.148501  14.524706
7              7  49.619718   6.120219   4.645333
8              8  49.603324   6.082887  13.338696
9              9  49.605799   6.138155  14.991892
10            10  49.586350   6.172555   6.611912
11            11  49.610249   6.107666  51.230000
12            12  49.609867   6.043061   2.795000
13            13  49.604930   6.157979   1.123143
14            14  49.610236   6.137252   0.396842
15            15  49.633201   6.162915   2.659041
16            16  49.598676   6.138281  38.458205
17            17  49.589373   6.106605   1.731944
18            18  49.589383   6.108860   2.999767
19            19  49.621218   6.167784   2.404706
20            20  49.575140   6.127124   6.668696
21            21  49.560618   6.162343   3.064545
22            22  49.615145   6.163218   0.467857
23            23  49.616792   6.130971   0.459286
24            24  49.589685   6.139084  11.451081
25            25  49.606426   6.056715   1.190000
26            26  49.606244   6.145407   8.622121
27            27  49.614134   6.155214   5.819222
28            28  49.614293   6.108941   3.482000
29            29  49.584032   6.114018   1.576774
...          ...        ...        ...        ...
3493        3493  49.578030   6.133560  44.322222
3494        3494  49.593595   6.129408   0.463500
3495        3495  49.571437   6.146372  15.303514
3496        3496  49.601563   6.056509   2.084390
3497        3497  49.629088   6.175081   1.104211
3498        3498  49.619548   6.094111   2.750444
3499        3499  49.597451   6.120221   5.809714
3500        3500  49.602474   6.072558   6.382727
3501        3501  49.613776   6.173606   5.084444
3502        3502  49.564533   6.163201   6.755897
3503        3503  49.594630   6.115967   5.442162
3504        3504  49.627482   6.199512   1.346667
3505        3505  49.610455   6.078737   1.023750
3506        3506  49.569455   6.149226   2.449310
3507        3507  49.592128   6.081991  17.896522
3508        3508  49.610610   6.079281   3.634545
3509        3509  49.631586   6.162574   1.674348
3510        3510  49.601466   6.132811   6.497750
3511        3511  49.600280   6.090701   0.760625
3512        3512  49.642984   6.127137   1.851154
3513        3513  49.597669   6.150221  10.124146
3514        3514  49.614495   6.117301   0.484000
3515        3515  49.570484   6.144995   2.045769
3516        3516  49.629352   6.134888   0.403000
3517        3517  49.601950   6.144802   0.261250
3518        3518  49.619443   6.163966   2.972424
3519        3519  49.615052   6.122346  47.332273
3520        3520  49.580313   6.111787   2.031613
3521        3521  49.583505   6.114780   1.523333
3522        3522  49.593817   6.120984   3.298000

[3523 rows x 4 columns]

b) Implement the Mean-Squared-Error function:
$$
MSE = \frac{1}{N_{Test}} \sum_{(x,y)\in D_{Test}} (f(x) - y)^2
$$
and a simple baseline model, which always predicts the mean
$$
f_{base}(x) = \frac{1}{N_{Train}} \sum_{(x,y)\in D_{Train}} y
$$
Test its performance with a $10-$fold cross validation and the test set. 

*Note: The jupyter notebook file already contains the necessary template to integrate your own classifier into `sklearn`*

In [ ]:
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.utils.multiclass import unique_labels

class BaselineModel(BaseEstimator, RegressorMixin):
    def __init__(self):
        #We do not have any parameters
        pass
    
    def fit(self, X, y):
        # Check that X and y have correct shape
        X, y = check_X_y(X, y)

        # Store the classes seen during fit. Since we will do regression, this is not necessary
        # self.classes_ = unique_labels(y)

        self.X_ = X
        self.y_ = y

        # The actual classifier's fit method
        # TODO

        # Return the classifier
        return self

    def predict(self, X):
        # Check is fit had been called
        check_is_fitted(self, ['X_', 'y_'])

        # Input validation
        X = check_array(X)
        
        # actual predict method
        # TODO
        
        return 0 # return prediction here

In [ ]:
import numpy as np
from sklearn.dummy import DummyRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.model_selection import cross_val_score

def mse(Y,YPredicted):
    # TODO


my_scorer = make_scorer(mse)

xvalScores = []

meanModel = BaselineModel();
scores = cross_val_score(meanModel, XTrain, YTrain, cv = 10, scoring=my_scorer) 
score = np.mean(scores)

meanModel = BaselineModel();
meanModel.fit(XTrain,YTrain)
print("MSE training = ", score)    
print("MSE test = ", mse(YTest, meanModel.predict(XTest)))  

c) Traffic counts have a large variance, which makes the results difficult to interpret. The Standardized Mean Squared Error
$$
SMSE = \frac{1}{N_{Test}\cdot var( D_{Test})} \sum_{(x,y)\in D_{Test}} (f(x) - y)^2
$$
standardized the MSE by also taking into account the variance $var( D_{Test})$ of the lables in the test data. Implement the SMSE and use it to rate the baseline model. What happens and why?

In [ ]:
import numpy as np
from sklearn.dummy import DummyRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.model_selection import cross_val_score

def smse(Y,YPred):
    # TODO

my_scorer = make_scorer(smse)

xvalScores = []

meanModel = BaselineModel();
scores = cross_val_score(meanModel, XTrain, YTrain, cv = 10, scoring=my_scorer) 
score = np.mean(scores)

meanModel = BaselineModel();
meanModel.fit(XTrain,YTrain)
print("MSE training = ", score)    
print("MSE test = ", mse(YTest, meanModel.predict(XTest)))     

d) Implement the K-Nearest-Neigbour algorithm and try different $K\in\{1,\dots,20\}$. What is the best configuration and what is its performance?

In [ ]:
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.utils.multiclass import unique_labels

class MyKNN(BaseEstimator, RegressorMixin):
    def __init__(self, K):
        self.K = K

    def fit(self, X, y):
        # Check that X and y have correct shape
        X, y = check_X_y(X, y)

        # Store the classes seen during fit. Since we will do regression, this is not necessary
        #self.classes_ = unique_labels(y)

        self.X_ = X
        self.y_ = y

        # The actual classifier's fit method
        # TODO

        # Return the classifier
        return self

    def predict(self, X):
        # Check is fit had been called
        check_is_fitted(self, ['X_', 'y_'])

        # Input validation
        X = check_array(X)

        # actual predict method
        # TODO
        return 0 # return prediction here

In [ ]:
# TODO: Validating on parameters and chosing best.